version: '2'

services:
  database:
    image: library/postgres:9.2
    environment:
      - POSTGRES_USER=stat_compiled
      - POSTGRES_PASSWORD=stat_compiled
      - POSTGRES_DB=statistics
    volumes:
      - ./tests/integrations/docker/database/init_database.sql:/docker-entrypoint-initdb.d/init_database.sql
  spark-stat-analyser:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: ["./tests/integrations/docker/wait-for-postgres.sh", "./run_test.sh"]
    environment:
      - STAT_DATABASE_HOST=database
      - STAT_DATABASE_DBNAME=statistics
      - STAT_DATABASE_USER=stat_compiled
      - STAT_DATABASE_PASSWORD=stat_compiled
    links:
      - database
    depends_on:
      - database
