FROM gettyimages/spark:2.1.0-hadoop-2.7

WORKDIR /srv/spark-stat-analyzer

RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get -yq install \
        libpq-dev \
        python3-dev \
        build-essential \
        && \
    rm -rf /var/lib/apt/lists/*

ADD requirements-test.txt /tmp/
RUN pip3 install -r requirements-test.txt

VOLUME /srv/spark-stat-analyzer

CMD ["./run_test.sh"]
